#!/usr/bin/env python3
"""Generate narasi audio (id-ID-ArdiNeural) untuk slide Pertemuan 2 PBO PHP.

- Menulis 24 MP3 ke docs/public/audio/pemrograman-oop-php/m2/slide-XX.mp3
- Menginjeksi array audioTranscripts ke dalam HTML presentasi.
"""
import asyncio
import json
from pathlib import Path

import edge_tts

ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "docs" / "public" / "presentasi" / "pertemuan-2-class-object-php.html"
AUDIO_DIR = ROOT / "docs" / "public" / "audio" / "pemrograman-oop-php" / "m2"
VOICE = "id-ID-ArdiNeural"
RATE = "+0%"

TRANSCRIPTS = [
    "Assalamualaikum dan selamat pagi rekan-rekan mahasiswa. Selamat datang kembali di mata kuliah Pemrograman Berorientasi Objek dengan PHP 8 plus. Saya Mahendar Dwi Payana, dosen pengampu kelas ini. Pada pertemuan kedua hari ini, kita akan membahas Class, Object, dan Perilaku di PHP 8 plus. Jika pertemuan pertama kita memahami mengapa OOP itu penting, maka hari ini kita akan benar-benar menulis benda-benda tersebut ke dalam kode. Kita akan berkenalan dengan typed properties, method, instansiasi, variabel this, hingga rahasia cara PHP mengelola memori objek. Mari kita mulai dengan semangat.",
    "Sebelum masuk ke materi, mari kita lakukan rekap singkat. Pada pertemuan pertama, kita sudah membahas paradigma OOP, empat pilar, fitur modern PHP, dan Composer. Hari ini target capaian pembelajaran kita adalah sub CPMK dua: mendefinisikan Class dan Object, mendeklarasikan typed properties dan method, melakukan instansiasi dengan kata kunci new, menggunakan variabel this, serta memahami cara PHP mengelola memori objek. Agenda kita terbagi empat: blueprint atau cetak biru, perilaku objek, jebakan dan memori, dan yang terakhir praktikum membuat class Produk untuk sistem kasir.",
    "Mari kita mulai dari konsep paling fundamental. Class adalah cetak biru atau blueprint. Ia mendefinisikan properti sebagai data dan method sebagai perilaku. Pada tahap ini, class belum memakan memori data. Object adalah wujud konkret dari class yang sudah dialokasikan di memori oleh Zend Engine, mesin di balik PHP. Setiap object memiliki salinan datanya sendiri yang disebut state. Analoginya sederhana: class adalah resep kue, dan object adalah kue yang sudah dipanggang. Satu resep class Mahasiswa bisa melahirkan tiga object dengan data berbeda: Ahmad, Rina, dan Budi, masing-masing dengan NIM dan IPK-nya sendiri.",
    "Sekarang mari kita bedah anatomi sebuah class. Di dalam class Mahasiswa, ada dua jenis penghuni. Pertama, properti atau atribut, yaitu tempat menyimpan data seperti nim, nama, jurusan, dan ipk. Kedua, method atau perilaku, contohnya belajar dan cetakInfo. Perhatikan bahwa kita selalu mengawali file dengan declare strict types sama dengan satu. Ini memaksa PHP menolak tipe data yang salah sejak awal. Perhatikan juga bahwa properti nim dan nama tidak memiliki nilai default. Ini berarti keduanya wajib diisi sebelum dibaca, atau akan terjadi fatal error yang akan kita bahas pada slide dua belas.",
    "PHP tujuh koma empat memperkenalkan typed properties. Artinya setiap properti wajib jujur soal tipenya. Formatnya: visibility, tipe, lalu nama properti. Misalnya public string nama, atau private float saldo. Memberi nilai default bersifat opsional. Jika properti jurusan diberi default Sistem Informasi, ia aman dibaca kapan saja. Sebaliknya, properti tanpa default wajib diisi manual terlebih dahulu. Keuntungan utamanya adalah keamanan. Jika Anda mencoba mengisi properti ipk yang bertipe float dengan string, PHP akan langsung melempar TypeError. Dengan demikian, integritas data terjaga sejak pintu masuk. Tipe yang sering dipakai antara lain string, int, float, bool, array, dan nullable string.",
    "Jika properti menyimpan keadaan, maka method melakukan aksi. Method adalah nyawa dari sebuah object. Perhatikan konvensi penulisannya: nama method menggunakan camelCase dan biasanya berupa kata kerja, seperti hitungLuas atau cetakInfo. Parameter dan nilai kembalian juga sebaiknya bertipe jelas. Kata kunci void berarti method tersebut tidak mengembalikan nilai. Di dalam method, kita mengakses data milik object sendiri melalui this, yaitu this panah nama properti. Ingat prinsipnya: method adalah satu-satunya pintu resmi menuju data object. Semua logika dan validasi sebaiknya diletakkan di sini, bukan tercecer di luar class.",
    "Ada tiga operator akses yang wajib Anda kuasai, dan sering tertukar. Pertama, operator panah, digunakan untuk mengakses properti dan method dari sebuah instance atau object. Contohnya mhs panah nama. Kedua, operator scope resolution atau titik dua ganda, digunakan untuk mengakses member static atau konstanta class. Ini akan kita bahas di pertemuan tiga. Ketiga, operator nullsafe yang diperkenalkan di PHP delapan, ditulis dengan tanda tanya panah. Ia membuat chaining menjadi aman ketika sebuah nilai mungkin bernilai null. Kesalahan favorit pemula adalah menambahkan tanda dolar setelah panah, seperti mhs panah dolar nama. Ingat, setelah panah, tulis nama member tanpa tanda dolar.",
    "Sekarang saatnya menghidupkan object dengan kata kunci new. Perhatikan kode berikut. Kita membuat dua object dari satu class Mahasiswa yang sama. Object pertama mhs1 diisi data Ahmad Pratama dengan IPK tiga koma delapan lima. Object kedua mhs2 diisi Rina Melati, dan kita mengubah jurusannya menjadi Informatika. Ketika kita panggil method cetakInfo pada mhs1, hasilnya tetap Sistem Informasi. Inilah bukti bahwa state setiap object itu mandiri. Mengubah data pada mhs2 tidak akan menginjak data pada mhs1. Satu class, banyak object, masing-masing dengan datanya sendiri.",
    "Mari kita bahas variabel khusus this secara lebih dalam. Di dalam sebuah method, this otomatis merujuk kepada object yang sedang memanggil method tersebut. Kita tidak perlu mengirimnya sebagai parameter. Perhatikan class PersegiPanjang. Method hitungLuas mengembalikan this panah panjang dikali this panah lebar. Ketika kita memanggil pp panah hitungLuas, maka this di dalam method merujuk pada object pp. Jika object lain memanggil method yang sama, this akan merujuk ke object itu. Jadi, ganti object-nya, maka isi this pun berganti. Itulah keajaiban reuse dalam OOP.",
    "Mari kita uji pemahaman dengan latihan menebak. Bayangkan ada dua object, a dan b, dengan ukuran berbeda. Ketika a memanggil hitungLuas, this merujuk pada a, dan hasilnya lima puluh. Ketika b memanggil hitungLuas, this merujuk pada b, dan hasilnya dua puluh satu. Lalu ketika a kembali memanggil hitungKeliling, this kembali merujuk pada a, menghasilkan tiga puluh. Pertanyaannya, kenapa method yang sama bisa menghasilkan angka berbeda? Jawabannya, karena this berganti mengikuti pemanggil. Method-nya hanya satu, tersimpan di class, tetapi datanya banyak, tersebar di tiap object. Inilah inti dari reuse di dalam OOP.",
    "Kita sudah memahami cara membuat dan menghidupkan object. Namun, ada dua hal yang paling sering menjebak pemula PHP delapan, yaitu error properti yang belum diinisialisasi, dan cara PHP menyimpan object di memori. Mari kita bahas keduanya, karena dua topik ini sangat sering muncul di UTS dan wawancara kerja.",
    "Mari kita bahas error yang wajib dihafal: uninitialized typed property. Jika Anda mendeklarasikan properti bertipe tanpa nilai default, lalu membacanya sebelum diisi, PHP tidak memberi peringatan biasa. PHP langsung menghentikan eksekusi total dengan fatal error, yang berbunyi: typed property Mahasiswa dollar nama must not be accessed before initialization. Error ini muncul di UTS hampir setiap tahun. Ada tiga solusi. Pertama, isi dulu propertinya, baru dibaca. Kedua, berikan nilai default langsung di class. Ketiga, buat properti menjadi nullable dengan tanda tanya dan nilai default null. Ingat urutannya: new, isi properti, baru panggil method. Jangan dibalik.",
    "Mari kita rangkum menjadi sebuah checklist inisialisasi yang aman, agar Anda tidak pernah kena error tersebut lagi. Pola pertama, gunakan default value untuk data yang punya nilai wajar awal, misalnya ipk nol koma nol, stok nol, atau jurusan Sistem Informasi. Pola kedua, gunakan nullable untuk data yang memang boleh kosong, misalnya wali, lalu cek dengan operator nullsafe. Pola ketiga, isi properti seusai new. Pola keempat, dan ini yang paling elegan, adalah menggunakan constructor. Pada pertemuan tiga nanti, kita akan mewajibkan pengisian data melalui constructor plus constructor promotion. Dengan begitu, error uninitialized ini akan punah dengan sendirinya.",
    "Sekarang kita masuk ke rahasia memori. Di PHP, variabel object tidak menyimpan nilai mentah, melainkan menyimpan object identifier atau handle. Jadi, ketika Anda menulis b sama dengan a, yang disalin adalah handle-nya, bukan bendanya. Mari kita lihat contohnya. Kita buat object a dengan nama Budi. Lalu b sama dengan a. Ketika kita mengubah nama melalui b menjadi Siti, ternyata a pun berubah menjadi Siti. Kenapa? Karena a dan b menunjuk ke object yang sama di memori. Analoginya seperti dua remote yang mengendalikan satu televisi. Ubah melalui remote satu, maka yang terlihat di televisi itu juga berubah.",
    "Lalu bagaimana jika kita benar-benar butuh object kembar yang independen, atau fotokopi yang sesungguhnya? Gunakan kata kunci clone. Ketika kita menulis c sama dengan clone a, PHP membuat duplikat fisik yang terpisah di memori. Sekarang, jika kita mengubah nama melalui c menjadi Andi, maka a tetap Siti. Mari kita bandingkan. Assignment biasa menghasilkan satu object yang dibagi. Clone menghasilkan dua object yang terpisah. Pertanyaan ujian yang paling favorit adalah: berapa object yang tercipta? Hitunglah jumlah new ditambah clone, bukan jumlah variabelnya.",
    "Sebelum masuk praktikum, mari kita bicara soal disiplin file. Aturan mainnya: satu class, satu file. Simpan class Mahasiswa di file Mahasiswa.php, dan letakkan kode eksekusinya di main.php atau index.php. Nama file harus sama dengan nama class. Class diawali huruf besar atau PascalCase, sedangkan method menggunakan camelCase. Dengan cara ini, proyek Anda tidak akan menjadi sarang require yang berantakan. Nanti pada pertemuan sembilan, require once manual ini akan kita ganti dengan autoloading Composer berbasis PSR empat.",
    "Teori kita sudah lengkap. Sekarang saatnya praktikum terbimbing. Kita akan membangun sebuah class Produk untuk sistem kasir sederhana. Class ini akan menerapkan semua teori hari ini: typed properties, method dengan validasi, penggunaan this, dan pengelolaan state. Mari kita mulai.",
    "Ini adalah kerangka class Produk. Ia memiliki empat properti: kode, nama, harga, dan stok. Perhatikan, properti stok diberi nilai default nol sehingga aman dibaca kapan saja. Sedangkan kode, nama, dan harga tidak diberi default, sehingga wajib diisi terlebih dahulu. Perhatikan juga method tambahStok. Di dalamnya ada validasi: jika jumlah lebih besar dari nol, baru stok ditambahkan. Jika tidak, kita tampilkan pesan kesalahan. Inilah pola validasi yang benar. Tolak input yang tidak valid di pintu method, dan jangan biarkan properti diisi langsung tanpa pemeriksaan.",
    "Selanjutnya, method jual. Ini adalah logika bisnis yang sesungguhnya. Pertama, kita cek apakah jumlah yang dijual valid, yaitu lebih besar dari nol. Kedua, kita cek apakah stok mencukupi. Jika ya, kita kurangi stok, hitung subtotal, dan tampilkan pesan penjualan berhasil. Jika stok tidak cukup, kita tampilkan peringatan dan mengembalikan nilai false. Pada contoh uji, stok awal adalah sepuluh. Jual tiga berhasil, menyisakan tujuh. Lalu jual sepuluh gagal, karena stok hanya tujuh. Terakhir, tambah stok lima, sehingga stok menjadi dua belas. Perhatikan bagaimana setiap perubahan state tercatat dengan rapi di dalam object.",
    "Saatnya kuis kilat tiga menit. Jawab dulu di dalam hati, baru buka jawabannya. Pertanyaan pertama: jika b sama dengan a, lalu b panah nama diisi Siti, berapa nilai a panah nama? Jawabannya adalah Siti, karena assignment object menyalin handle, bukan bendanya. Pertanyaan kedua: apa arti error must not be accessed before initialization? Itu berarti properti bertipe dibaca sebelum pernah diisi. Solusinya, isi dulu, beri default, atau buat nullable. Pertanyaan ketiga: di dalam method, apa isi this? Jawabannya, referensi ke object yang sedang memanggil method tersebut. Beda pemanggil, beda isi this, beda pula hasilnya.",
    "Mari kita lakukan latihan berpasangan. Dengan teman sebangku, trace program berikut di kertas, tanpa laptop. Kita mulai dengan object x yang memiliki stok lima. Lalu y sama dengan x, artinya y berbagi handle yang sama. y jual dua, sehingga stok menjadi tiga. Selanjutnya z sama dengan clone x, jadi z adalah fotokopi independen dengan stok tiga. z jual dua, menjadi satu. Pertanyaannya, berapa stok x dan berapa stok z? Jawabannya, x tetap tiga, karena tidak terpengaruh clone, sedangkan z bernilai satu. Waktu lima menit untuk trace, dua menit untuk pembahasan. Yang benar duluan mendapatkan poin partisipasi.",
    "Ini tugas mandiri Anda. Terapkan pola class Produk ke domain penggajian. Buat file Karyawan.php dengan properti idKaryawan, nama, divisi, gajiPokok, dan jumlahJamLembur yang default-nya nol. Tambahkan empat method: tambahLembur, hitungUangLembur dengan tarif lima puluh ribu rupiah per jam, hitungTotalGaji, dan cetakSlipGaji. Lalu buat main.php yang menginstansiasi minimal dua object karyawan dengan jam lembur berbeda, dan cetak slip gaji keduanya. Kriteria penilaiannya: strict types, typed properties terisi penuh, validasi input, output yang rapi, dan repository GitHub yang terstruktur. Kumpulkan melalui GitHub dan LMS.",
    "Mari kita lihat posisi kita dalam roadmap satu semester. Pertemuan satu dan dua sudah selesai. Fondasi pembuatan object sudah kokoh. Berikutnya, pada pertemuan tiga, kita akan mengunci pengisian data sejak lahir melalui constructor, method chaining, static members, dan constructor promotion. Setelah itu, kita masuk ke encapsulation, inheritance, polymorphism, interface, hingga UTS. Paruh kedua semester kita akan mengeksplorasi namespace, exception, collection, file handling, SOLID, arsitektur aplikasi, capstone project, dan diakhiri UAS.",
    "Demikian pertemuan kedua kita. Kesimpulan hari ini: class adalah resep, object adalah kuenya, dan this adalah juru masak yang tahu kue mana yang sedang ia panggang. Pada pertemuan berikutnya, kita akan membahas constructor, method chaining, static members, dan constructor promotion, sehingga error uninitialized property akan punah selamanya. Silakan kerjakan tugas Karyawan dan pastikan environment PHP Anda sudah siap. Terima kasih atas perhatiannya, semoga ilmu hari ini bermanfaat. Wassalamualaikum warahmatullahi wabarakatuh.",
]


async def generate() -> None:
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    for i, text in enumerate(TRANSCRIPTS):
        num = str(i + 1).zfill(2)
        out = AUDIO_DIR / f"slide-{num}.mp3"
        communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
        await communicate.save(str(out))
        size = out.stat().st_size
        print(f"[{i+1:02d}/{len(TRANSCRIPTS)}] {out.name}  ({size/1024:.0f} KB)")


def inject_transcripts() -> None:
    html = HTML.read_text(encoding="utf-8")
    payload = json.dumps(TRANSCRIPTS, ensure_ascii=False)
    declaration = "const audioTranscripts=" + payload + ";\n"
    if "/*__TRANSCRIPTS__*/" in html:
        html = html.replace("const audioTranscripts=[/*__TRANSCRIPTS__*/];", declaration.strip())
    else:
        start = html.index("const audioTranscripts=")
        end = html.index("const audioPlayer=", start)
        html = html[:start] + declaration + html[end:]
    HTML.write_text(html, encoding="utf-8")
    print(f"Transcripts injected -> {HTML}")


if __name__ == "__main__":
    asyncio.run(generate())
    inject_transcripts()
